
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class uji_kebolehan extends javax.swing.JFrame {
    String temp ="";
    Double t1, bt, h1;
    /**
     * Creates new form uji_kebolehan
     */
    public uji_kebolehan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jeniskelamin = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        Tinggi = new javax.swing.JTextField();
        Berat = new javax.swing.JTextField();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        btnHitung = new javax.swing.JButton();
        btnCoba = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Hasil = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Diagnosa1 = new javax.swing.JTextField();
        Diagnosa2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 10, 140, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 50, 30, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Tinggi");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 90, 40, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Berat Badan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 130, 80, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 170, 80, 30);

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });
        getContentPane().add(Nama);
        Nama.setBounds(130, 50, 160, 30);
        getContentPane().add(Tinggi);
        Tinggi.setBounds(130, 90, 70, 30);
        getContentPane().add(Berat);
        Berat.setBounds(130, 130, 70, 30);

        Jeniskelamin.add(rbLaki);
        rbLaki.setText("Laki-laki");
        rbLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLakiActionPerformed(evt);
            }
        });
        getContentPane().add(rbLaki);
        rbLaki.setBounds(130, 170, 80, 30);

        Jeniskelamin.add(rbPerempuan);
        rbPerempuan.setText("Perempuan");
        getContentPane().add(rbPerempuan);
        rbPerempuan.setBounds(220, 170, 93, 30);

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        getContentPane().add(btnHitung);
        btnHitung.setBounds(33, 210, 80, 23);

        btnCoba.setText("Coba Lagi");
        btnCoba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCoba);
        btnCoba.setBounds(130, 210, 100, 23);

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar);
        btnKeluar.setBounds(250, 210, 90, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Berat badan ideal Anda adalah");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 250, 210, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("kg");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(320, 250, 20, 40);

        Hasil.setEditable(false);
        getContentPane().add(Hasil);
        Hasil.setBounds(240, 250, 70, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 255));
        jLabel8.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(100, 290, 170, 20);

        Diagnosa1.setEditable(false);
        getContentPane().add(Diagnosa1);
        Diagnosa1.setBounds(40, 320, 310, 30);

        Diagnosa2.setEditable(false);
        getContentPane().add(Diagnosa2);
        Diagnosa2.setBounds(40, 360, 310, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("cm");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(210, 90, 20, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("kg");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(210, 130, 20, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void btnCobaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobaActionPerformed
        // TODO add your handling code here:
        Nama.setText("");
        Tinggi.setText("");
        Berat.setText("");
        Jeniskelamin.clearSelection();
        Hasil.setText("");
        Diagnosa1.setText("");
        Diagnosa2.setText("");
    }//GEN-LAST:event_btnCobaActionPerformed

    private void rbLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLakiActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        if (Nama.getText().equals("")||Tinggi.getText().equals("")||Berat.getText().equals("")){
        JOptionPane.showMessageDialog(null, "Data inputan harus diisi");
        }else if(rbLaki.isSelected()||rbPerempuan.isSelected()){
        try{
        Proses();
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Data harus diisi");
        }
        }else{
            JOptionPane.showMessageDialog(null, "Jenis Kelamin belum dipilih");
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uji_kebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uji_kebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uji_kebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uji_kebolehan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uji_kebolehan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Berat;
    private javax.swing.JTextField Diagnosa1;
    private javax.swing.JTextField Diagnosa2;
    private javax.swing.JTextField Hasil;
    private javax.swing.ButtonGroup Jeniskelamin;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Tinggi;
    private javax.swing.JButton btnCoba;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        t1 = Double.valueOf(Tinggi.getText());
        bt = Double.valueOf(Berat.getText());
        
        
        if (rbLaki.isSelected()){
        h1 = (t1-100) * 1;
        }else if(rbPerempuan.isSelected()){
        h1 = (t1-104)*1;
        }
        temp = Double.toString(h1.intValue());
        
        if (h1<bt){
        Hasil.setText(temp);
        Diagnosa1.setText("Hasil "+ Nama.getText() + ". Sepertinya Anda Overweight :( ");
        Diagnosa2.setText("Banyaklah berolahraga dan hindari makanan berkolesterol");
        } else if (h1>bt){
        Hasil.setText(temp);
        Diagnosa1.setText("Hasil "+ Nama.getText() + ". Sepertinya Anda Underweight :( ");
        Diagnosa2.setText("Banyaklah mengkonsumsi makanan yang berkarbohidrat");
        }else{
        Hasil.setText(temp);
        Diagnosa1.setText("Hasil "+ Nama.getText() + ". Berat badan Anda sudah ideal :)");
        Diagnosa2.setText("Lanjutkan pola makan teratur dan gaya hidup sehat :)");
        }

    }
}
